//// Gleam language, ecosystem, and Lustre quiz content.

import quiz/domain.{
  type Question, type Quiz, Answer, Correct, Incorrect, Question, Quiz,
}

// QUIZ ------------------------------------------------------------------------

pub fn quiz() -> Quiz {
  Quiz(
    id: "gleam",
    title: "Gleam",
    description: "100 questions about the Gleam language, ecosystem, and Lustre.",
    questions: questions(),
  )
}

// QUESTIONS -------------------------------------------------------------------

/// Return the canonical question bank.
///
/// Keep the correct answer first here to make questions easy to author and review.
/// The application uses shuffled to randomise both levels for each quiz run.
fn questions() -> List(Question) {
  [
    Question(
      prompt: "What do the variants of a Gleam custom type represent?",
      answers: [
        Answer(
          text: "The different shapes a value of that type can have",
          correctness: Correct,
        ),
        Answer(
          text: "Methods inherited by each value from the custom type's shared base class",
          correctness: Incorrect,
        ),
        Answer(text: "Runtime subclasses", correctness: Incorrect),
        Answer(text: "Files generated by the compiler", correctness: Incorrect),
      ],
      explanation: "Each constructor defines one possible shape of the custom type. Pattern matching lets you handle every shape explicitly.",
    ),
    Question(
      prompt: "What is a record in Gleam?",
      answers: [
        Answer(
          text: "A custom-type variant that contains labelled or positional fields",
          correctness: Correct,
        ),
        Answer(
          text: "A mutable object whose fields can be added and removed at runtime",
          correctness: Incorrect,
        ),
        Answer(text: "A row returned from a database", correctness: Incorrect),
        Answer(text: "A special kind of dictionary", correctness: Incorrect),
      ],
      explanation: "A record is a custom-type constructor that holds data. A single-variant custom type is often used like a struct.",
    ),
    Question(
      prompt: "What must a case expression do in Gleam?",
      answers: [
        Answer(text: "Match every possible value", correctness: Correct),
        Answer(text: "Return a Boolean", correctness: Incorrect),
        Answer(text: "Contain an else branch", correctness: Incorrect),
        Answer(text: "Perform a side effect", correctness: Incorrect),
      ],
      explanation: "Gleam checks case expressions for exhaustiveness, so adding a new variant can reveal every place that must handle it.",
    ),
    Question(
      prompt: "What does the list pattern [first, ..rest] establish?",
      answers: [
        Answer(
          text: "The list is non-empty, binding its first item and remaining items",
          correctness: Correct,
        ),
        Answer(
          text: "The list contains exactly two items bound to first and rest",
          correctness: Incorrect,
        ),
        Answer(text: "The list is sorted", correctness: Incorrect),
        Answer(text: "The list can be mutated", correctness: Incorrect),
      ],
      explanation: "The pattern only matches non-empty lists. An empty-list pattern is needed for the other possible shape.",
    ),
    Question(
      prompt: "What does [new_item, ..existing_items] do?",
      answers: [
        Answer(
          text: "Creates a new list with new_item at the front",
          correctness: Correct,
        ),
        Answer(
          text: "Mutates existing_items in place by shifting every item one position",
          correctness: Incorrect,
        ),
        Answer(text: "Appends new_item to the end", correctness: Incorrect),
        Answer(text: "Creates a nested list", correctness: Incorrect),
      ],
      explanation: "Gleam lists are immutable linked lists. Prepending creates a new front node and leaves the existing list unchanged.",
    ),
    Question(
      prompt: "Which value is a tuple containing an Int and a String?",
      answers: [
        Answer(text: "#(42, \"Gleam\")", correctness: Correct),
        Answer(text: "[42, \"Gleam\"]", correctness: Incorrect),
        Answer(text: "{42, \"Gleam\"}", correctness: Incorrect),
        Answer(text: "Tuple(42, \"Gleam\")", correctness: Incorrect),
      ],
      explanation: "Tuple syntax uses #(...). Unlike a list, a tuple can contain values of different types in fixed positions.",
    ),
    Question(
      prompt: "What does Gleam's Result type represent?",
      answers: [
        Answer(
          text: "A value that can be successful or contain an error",
          correctness: Correct,
        ),
        Answer(
          text: "A value that may be absent without carrying information about why",
          correctness: Incorrect,
        ),
        Answer(
          text: "A collection with exactly two items",
          correctness: Incorrect,
        ),
        Answer(text: "A delayed side effect", correctness: Incorrect),
      ],
      explanation: "Result(value, error) has the variants Ok(value) and Error(error), making failure part of the function's return type.",
    ),
    Question(
      prompt: "When is Option(value) the most natural model?",
      answers: [
        Answer(
          text: "When a value may be present or absent without error details",
          correctness: Correct,
        ),
        Answer(
          text: "When an operation has several error reasons that callers need to distinguish",
          correctness: Incorrect,
        ),
        Answer(text: "When a value changes over time", correctness: Incorrect),
        Answer(
          text: "When a function returns two values",
          correctness: Incorrect,
        ),
      ],
      explanation: "Option(value) has Some(value) and None. Use Result when the failure itself carries useful information.",
    ),
    Question(
      prompt: "What does the pipeline operator pass to the next function?",
      answers: [
        Answer(text: "The value on its left", correctness: Correct),
        Answer(text: "The function's return type", correctness: Incorrect),
        Answer(text: "The current module", correctness: Incorrect),
        Answer(text: "A list of all previous values", correctness: Incorrect),
      ],
      explanation: "The |> operator normally supplies the left-hand value as the first argument. A function capture can place it in another position.",
    ),
    Question(
      prompt: "What does the underscore mean in string.append(\"!\", _)?",
      answers: [
        Answer(
          text: "It captures a one-argument function with a placeholder",
          correctness: Correct,
        ),
        Answer(
          text: "It discards the return value and replaces that argument with an empty string",
          correctness: Incorrect,
        ),
        Answer(text: "It inserts an empty string", correctness: Incorrect),
        Answer(text: "It marks a private function", correctness: Incorrect),
      ],
      explanation: "Function capture syntax is shorthand for an anonymous function. Here it is equivalent to fn(value) { string.append(\"!\", value) }.",
    ),
    Question(
      prompt: "What makes a function higher-order?",
      answers: [
        Answer(
          text: "It accepts a function or returns a function",
          correctness: Correct,
        ),
        Answer(text: "It is declared with pub", correctness: Incorrect),
        Answer(
          text: "It contains more than one pipeline",
          correctness: Incorrect,
        ),
        Answer(text: "It works only with custom types", correctness: Incorrect),
      ],
      explanation: "Functions are ordinary values in Gleam, so they can be passed to and returned from other functions.",
    ),
    Question(
      prompt: "What does list.map([1, 2, 3], fn(x) { x * 2 }) return?",
      answers: [
        Answer(text: "[2, 4, 6]", correctness: Correct),
        Answer(text: "[1, 2, 3, 2]", correctness: Incorrect),
        Answer(text: "6", correctness: Incorrect),
        Answer(text: "Nil", correctness: Incorrect),
      ],
      explanation: "list.map applies the function to every element and returns a new list containing the transformed values.",
    ),
    Question(
      prompt: "What does pub change on a top-level Gleam definition?",
      answers: [
        Answer(
          text: "It makes the definition accessible from other modules",
          correctness: Correct,
        ),
        Answer(
          text: "It makes the value mutable and accessible to every module in the package",
          correctness: Incorrect,
        ),
        Answer(
          text: "It runs the definition at startup",
          correctness: Incorrect,
        ),
        Answer(text: "It publishes the package to Hex", correctness: Incorrect),
      ],
      explanation: "Top-level functions, constants, and types are private to their module unless they are declared public.",
    ),
    Question(
      prompt: "What does import gleam/string as text do?",
      answers: [
        Answer(
          text: "Imports the module under the local name text",
          correctness: Correct,
        ),
        Answer(
          text: "Imports only a function named text",
          correctness: Incorrect,
        ),
        Answer(text: "Converts every String to Text", correctness: Incorrect),
        Answer(text: "Renames the module globally", correctness: Incorrect),
      ],
      explanation: "A module alias only changes how that module is referred to within the importing module.",
    ),
    Question(
      prompt: "When should let assert be used?",
      answers: [
        Answer(
          text: "When failure means a programmer assumption was wrong",
          correctness: Correct,
        ),
        Answer(
          text: "For normal user-input validation when detailed error messages are unnecessary",
          correctness: Incorrect,
        ),
        Answer(
          text: "Whenever a function returns Result",
          correctness: Incorrect,
        ),
        Answer(
          text: "To disable exhaustiveness checking",
          correctness: Incorrect,
        ),
      ],
      explanation: "let assert permits a pattern that may fail and panics if it does. Recoverable possibilities should be handled explicitly instead.",
    ),
    Question(
      prompt: "What is the main purpose of a use expression?",
      answers: [
        Answer(
          text: "To write callback-based control flow without deep nesting",
          correctness: Correct,
        ),
        Answer(
          text: "To import another module only for the duration of one expression block",
          correctness: Incorrect,
        ),
        Answer(text: "To mutate a value temporarily", correctness: Incorrect),
        Answer(text: "To catch every runtime exception", correctness: Incorrect),
      ],
      explanation: "A use expression passes the remainder of its block as a callback, making patterns such as Result sequencing read top-to-bottom.",
    ),
    Question(
      prompt: "What does Person(..person, age: 31) do?",
      answers: [
        Answer(
          text: "Creates a new record using person's fields with a new age",
          correctness: Correct,
        ),
        Answer(
          text: "Mutates person's age in place while retaining the identity of the original record",
          correctness: Incorrect,
        ),
        Answer(
          text: "Pattern matches only the age field",
          correctness: Incorrect,
        ),
        Answer(text: "Converts person into a tuple", correctness: Incorrect),
      ],
      explanation: "Record update syntax constructs a new value by copying existing fields and replacing the named fields. The original remains unchanged.",
    ),
    Question(
      prompt: "What does pub opaque type protect?",
      answers: [
        Answer(
          text: "Its constructors and internal representation outside its module",
          correctness: Correct,
        ),
        Answer(
          text: "The type's source code and all functions that operate on it from the compiler",
          correctness: Incorrect,
        ),
        Answer(
          text: "All functions that accept the type",
          correctness: Incorrect,
        ),
        Answer(
          text: "The value from garbage collection",
          correctness: Incorrect,
        ),
      ],
      explanation: "Other modules can hold an opaque value and use the defining module's public API, but they cannot construct or pattern match on its hidden representation.",
    ),
    Question(
      prompt: "When can Gleam infer a function's types?",
      answers: [
        Answer(
          text: "When the implementation and its uses provide enough information",
          correctness: Correct,
        ),
        Answer(
          text: "Only when every argument and return value can be inferred to have the same type",
          correctness: Incorrect,
        ),
        Answer(
          text: "Only for private functions with no arguments",
          correctness: Incorrect,
        ),
        Answer(
          text: "Never; every type must be annotated",
          correctness: Incorrect,
        ),
      ],
      explanation: "Gleam performs full static type inference. Function annotations are still good documentation and help communicate intent.",
    ),
    Question(
      prompt: "How does a Gleam function return a value normally?",
      answers: [
        Answer(
          text: "The final expression in its body becomes the return value",
          correctness: Correct,
        ),
        Answer(
          text: "It must use a return keyword followed by the final expression's value",
          correctness: Incorrect,
        ),
        Answer(text: "It assigns the value to result", correctness: Incorrect),
        Answer(text: "It sends the value to the caller", correctness: Incorrect),
      ],
      explanation: "Gleam is expression-oriented. Blocks and function bodies evaluate to their final expression, so there is no ordinary return keyword.",
    ),
    Question(
      prompt: "What is the result of 5 / 2 in Gleam?",
      answers: [
        Answer(text: "2", correctness: Correct),
        Answer(text: "2.5", correctness: Incorrect),
        Answer(text: "2.0", correctness: Incorrect),
        Answer(text: "Error(Division)", correctness: Incorrect),
      ],
      explanation: "Both operands are Int values, so / performs integer division. Gleam does not implicitly convert between Int and Float.",
    ),
    Question(
      prompt: "Which operator adds two Float values in Gleam?",
      answers: [
        Answer(text: "+.", correctness: Correct),
        Answer(text: "+", correctness: Incorrect),
        Answer(text: "++", correctness: Incorrect),
        Answer(text: "<>", correctness: Incorrect),
      ],
      explanation: "Numeric operators are not overloaded. Float arithmetic uses operators such as +., -., *., and /., while Int arithmetic omits the dot.",
    ),
    Question(
      prompt: "Which operator concatenates two strings?",
      answers: [
        Answer(text: "<>", correctness: Correct),
        Answer(text: "+", correctness: Incorrect),
        Answer(text: "++", correctness: Incorrect),
        Answer(text: "|>", correctness: Incorrect),
      ],
      explanation: "The <> operator joins strings. The + operator is reserved for Int addition, so there is no overloaded string addition.",
    ),
    Question(
      prompt: "How does Gleam compare values with ==?",
      answers: [
        Answer(
          text: "Structurally, with both sides required to have the same type",
          correctness: Correct,
        ),
        Answer(
          text: "By comparing runtime memory addresses after converting both values to objects",
          correctness: Incorrect,
        ),
        Answer(
          text: "By converting both sides to strings",
          correctness: Incorrect,
        ),
        Answer(
          text: "Only primitive values can be compared",
          correctness: Incorrect,
        ),
      ],
      explanation: "Equality works across Gleam types and compares their structure rather than object identity. The two operands must share a type.",
    ),
    Question(
      prompt: "Which statement about null is true in Gleam?",
      answers: [
        Answer(
          text: "Ordinary Gleam values cannot implicitly be null",
          correctness: Correct,
        ),
        Answer(
          text: "Every custom type includes null unless all constructors contain fields",
          correctness: Incorrect,
        ),
        Answer(text: "Strings become null when empty", correctness: Incorrect),
        Answer(text: "Null and Nil are interchangeable", correctness: Incorrect),
      ],
      explanation: "Absence is represented explicitly with types such as Option. Nil is a real type with one value, not an implicit missing value.",
    ),
    Question(
      prompt: "What is true when calling a function with labelled arguments?",
      answers: [
        Answer(
          text: "Labelled arguments can be supplied in a different order",
          correctness: Correct,
        ),
        Answer(
          text: "Labels create a runtime dictionary mapping argument names to supplied values",
          correctness: Incorrect,
        ),
        Answer(text: "Every argument must have a label", correctness: Incorrect),
        Answer(
          text: "Labels change the argument's type",
          correctness: Incorrect,
        ),
      ],
      explanation: "Labels improve readability and can be reordered at the call site. Unlabelled arguments must still come before labelled ones.",
    ),
    Question(
      prompt: "What does the a mean in List(a)?",
      answers: [
        Answer(
          text: "A type parameter representing the list's element type",
          correctness: Correct,
        ),
        Answer(
          text: "The name assigned to the first item stored in every non-empty list",
          correctness: Incorrect,
        ),
        Answer(text: "A module alias", correctness: Incorrect),
        Answer(text: "The list's memory address", correctness: Incorrect),
      ],
      explanation: "Lowercase type variables make a definition generic. List(Int) and List(String) use the same List type with different element types.",
    ),
    Question(
      prompt: "What does case x, y { ... } enable?",
      answers: [
        Answer(
          text: "Pattern matching on multiple values at the same time",
          correctness: Correct,
        ),
        Answer(
          text: "Running two case expressions concurrently",
          correctness: Incorrect,
        ),
        Answer(text: "Combining x and y into a list", correctness: Incorrect),
        Answer(text: "Ignoring the value of y", correctness: Incorrect),
      ],
      explanation: "A case expression can have multiple subjects. Every clause then supplies the same number of comma-separated patterns.",
    ),
    Question(
      prompt: "What is the purpose of a guard on a case clause?",
      answers: [
        Answer(
          text: "To add a Boolean condition after a pattern matches",
          correctness: Correct,
        ),
        Answer(text: "To catch runtime exceptions", correctness: Incorrect),
        Answer(
          text: "To make a private constructor public",
          correctness: Incorrect,
        ),
        Answer(
          text: "To prevent the compiler from checking the clause",
          correctness: Incorrect,
        ),
      ],
      explanation: "A guard refines a matching clause with an additional condition. If the guard is false, matching continues with later clauses.",
    ),
    Question(
      prompt: "How is custom iteration usually expressed in Gleam?",
      answers: [
        Answer(
          text: "With recursion, often hidden behind standard-library functions",
          correctness: Correct,
        ),
        Answer(
          text: "With mutable for loops supplied by the JavaScript runtime",
          correctness: Incorrect,
        ),
        Answer(text: "With goto labels", correctness: Incorrect),
        Answer(text: "By modifying a global counter", correctness: Incorrect),
      ],
      explanation: "Gleam has no loop statements. Common iterations use functions such as list.map and list.fold, while custom loops use recursion.",
    ),
    Question(
      prompt: "When can a recursive call be tail-call optimised?",
      answers: [
        Answer(
          text: "When the recursive call is the final operation",
          correctness: Correct,
        ),
        Answer(
          text: "Whenever the function is public and all recursive arguments can be inferred",
          correctness: Incorrect,
        ),
        Answer(text: "Only when processing strings", correctness: Incorrect),
        Answer(
          text: "When the function has no base case",
          correctness: Incorrect,
        ),
      ],
      explanation: "A tail call lets the runtime reuse the current stack frame. Accumulators often help move remaining work into the recursive call's arguments.",
    ),
    Question(
      prompt: "What does list.filter keep?",
      answers: [
        Answer(
          text: "Elements for which its predicate returns True",
          correctness: Correct,
        ),
        Answer(text: "Only the first element", correctness: Incorrect),
        Answer(text: "The predicate's return values", correctness: Incorrect),
        Answer(
          text: "Elements for which the predicate returns False",
          correctness: Incorrect,
        ),
      ],
      explanation: "list.filter returns a new list containing the original elements accepted by the predicate.",
    ),
    Question(
      prompt: "What is list.fold useful for?",
      answers: [
        Answer(
          text: "Combining a list into an accumulated result",
          correctness: Correct,
        ),
        Answer(text: "Sorting a list in place", correctness: Incorrect),
        Answer(
          text: "Turning every item into a separate list",
          correctness: Incorrect,
        ),
        Answer(text: "Reading an item by index", correctness: Incorrect),
      ],
      explanation: "list.fold walks left-to-right, passing an accumulator and each element to a function that produces the next accumulator.",
    ),
    Question(
      prompt: "What does list.find return when no element matches?",
      answers: [
        Answer(text: "Error(Nil)", correctness: Correct),
        Answer(text: "None", correctness: Incorrect),
        Answer(text: "False", correctness: Incorrect),
        Answer(text: "An empty list", correctness: Incorrect),
      ],
      explanation: "list.find returns Result(element, Nil): Ok(element) for the first match and Error(Nil) when there is no match.",
    ),
    Question(
      prompt: "What does result.map do with an Error value?",
      answers: [
        Answer(
          text: "Returns the Error without calling the mapping function",
          correctness: Correct,
        ),
        Answer(
          text: "Converts Error into Ok before passing its payload to the mapping function",
          correctness: Incorrect,
        ),
        Answer(
          text: "Calls the mapping function with the error",
          correctness: Incorrect,
        ),
        Answer(text: "Panics immediately", correctness: Incorrect),
      ],
      explanation: "result.map transforms only the success value inside Ok. An existing Error passes through unchanged.",
    ),
    Question(
      prompt: "How does result.try differ from result.map?",
      answers: [
        Answer(
          text: "Its function returns another Result, allowing fallible steps to chain",
          correctness: Correct,
        ),
        Answer(
          text: "Its function retries a failed Result until the operation eventually succeeds",
          correctness: Incorrect,
        ),
        Answer(text: "It ignores Error values", correctness: Incorrect),
        Answer(
          text: "It works only with lists of results",
          correctness: Incorrect,
        ),
      ],
      explanation: "result.try applies a Result-returning function to an Ok value and stops at the first Error, avoiding nested Result values.",
    ),
    Question(
      prompt: "What does result.unwrap(Error(error), default) return?",
      answers: [
        Answer(text: "default", correctness: Correct),
        Answer(text: "error", correctness: Incorrect),
        Answer(text: "Nil", correctness: Incorrect),
        Answer(text: "It always panics", correctness: Incorrect),
      ],
      explanation: "result.unwrap extracts an Ok value or uses the supplied default when given an Error.",
    ),
    Question(
      prompt: "What is a Dict in Gleam's standard library?",
      answers: [
        Answer(
          text: "A collection that associates unique keys with values",
          correctness: Correct,
        ),
        Answer(
          text: "A list of key and value strings preserving the order entries were inserted",
          correctness: Incorrect,
        ),
        Answer(text: "A mutable global object", correctness: Incorrect),
        Answer(
          text: "A custom type with exactly two variants",
          correctness: Incorrect,
        ),
      ],
      explanation: "gleam/dict provides an immutable key-value collection, similar to a hashmap or table in other languages.",
    ),
    Question(
      prompt: "What distinguishes a Set from a List?",
      answers: [
        Answer(
          text: "A Set stores unique values without list ordering semantics",
          correctness: Correct,
        ),
        Answer(
          text: "A Set can contain unrelated types while a List has one element type",
          correctness: Incorrect,
        ),
        Answer(text: "A Set is mutable", correctness: Incorrect),
        Answer(
          text: "A Set always contains exactly two values",
          correctness: Incorrect,
        ),
      ],
      explanation: "gleam/set models membership of unique values. Lists preserve sequence and may contain duplicates.",
    ),
    Question(
      prompt: "What is echo primarily for?",
      answers: [
        Answer(
          text: "Debug-printing a value of any type while returning that value",
          correctness: Correct,
        ),
        Answer(
          text: "Rendering a textual representation of any value in the browser UI",
          correctness: Incorrect,
        ),
        Answer(
          text: "Converting any value into a String",
          correctness: Incorrect,
        ),
        Answer(text: "Sending a message to an actor", correctness: Incorrect),
      ],
      explanation: "echo is a debugging keyword. It prints the source location and value, then evaluates to that same value, so it can sit inside a pipeline.",
    ),
    Question(
      prompt: "What does @external allow a Gleam module to use?",
      answers: [
        Answer(
          text: "A function implemented in Erlang or JavaScript",
          correctness: Correct,
        ),
        Answer(text: "An untyped Gleam function", correctness: Incorrect),
        Answer(
          text: "A private function from another Gleam module",
          correctness: Incorrect,
        ),
        Answer(
          text: "A package that is not listed as a dependency",
          correctness: Incorrect,
        ),
      ],
      explanation: "External functions form the typed boundary to runtime-native code. Gleam trusts their declared types, so that boundary requires care.",
    ),
    Question(
      prompt: "What enables much Gleam code to run on both Erlang and JavaScript?",
      answers: [
        Answer(
          text: "The compiler supports both targets and shared Gleam code is portable",
          correctness: Correct,
        ),
        Answer(
          text: "JavaScript is translated into Erlang bytecode before either target runs",
          correctness: Incorrect,
        ),
        Answer(text: "Every function runs in a browser", correctness: Incorrect),
        Answer(
          text: "Both targets expose identical native APIs",
          correctness: Incorrect,
        ),
      ],
      explanation: "Pure Gleam code commonly works on either target. Target-specific externals and runtime capabilities can still limit portability.",
    ),
    Question(
      prompt: "What happens when a let binding reuses an existing variable name?",
      answers: [
        Answer(
          text: "A new binding shadows the earlier one",
          correctness: Correct,
        ),
        Answer(text: "The earlier value is mutated", correctness: Incorrect),
        Answer(text: "The compiler always rejects it", correctness: Incorrect),
        Answer(text: "Both values are merged", correctness: Incorrect),
      ],
      explanation: "Gleam values are immutable. Reusing a name creates a new binding that shadows the old one from that point onward.",
    ),
    Question(
      prompt: "Which naming style does Gleam require for functions and variables?",
      answers: [
        Answer(text: "snake_case", correctness: Correct),
        Answer(text: "camelCase", correctness: Incorrect),
        Answer(text: "PascalCase", correctness: Incorrect),
        Answer(text: "kebab-case", correctness: Incorrect),
      ],
      explanation: "Functions, variables, and module names use snake_case. Types and constructors use PascalCase.",
    ),
    Question(
      prompt: "What is the type of Nil?",
      answers: [
        Answer(text: "Nil", correctness: Correct),
        Answer(text: "Option(a)", correctness: Incorrect),
        Answer(text: "Bool", correctness: Incorrect),
        Answer(text: "List(a)", correctness: Incorrect),
      ],
      explanation: "Nil is both the single value and the name of its type. It is commonly used when no meaningful value needs to be carried.",
    ),
    Question(
      prompt: "What does a type alias create?",
      answers: [
        Answer(text: "Another name for an existing type", correctness: Correct),
        Answer(text: "A new incompatible runtime type", correctness: Incorrect),
        Answer(text: "A hidden custom-type constructor", correctness: Incorrect),
        Answer(text: "A mutable reference", correctness: Incorrect),
      ],
      explanation: "An alias improves readability but does not create a distinct type. Values of the alias and the original type are interchangeable.",
    ),
    Question(
      prompt: "Where must a Gleam module declaration be written?",
      answers: [
        Answer(
          text: "Nowhere; the file path determines the module name",
          correctness: Correct,
        ),
        Answer(
          text: "On the first line of every source file",
          correctness: Incorrect,
        ),
        Answer(text: "In gleam.toml for each file", correctness: Incorrect),
        Answer(text: "Inside the main function", correctness: Incorrect),
      ],
      explanation: "A source file's path under src or test determines its module name, so Gleam does not use an in-file module declaration.",
    ),
    Question(
      prompt: "What does import gleam/list.{map} make available?",
      answers: [
        Answer(
          text: "The map function without a module prefix",
          correctness: Correct,
        ),
        Answer(
          text: "Every function in gleam/list under a new local namespace named map",
          correctness: Incorrect,
        ),
        Answer(text: "Only the List type", correctness: Incorrect),
        Answer(text: "A new function named list_map", correctness: Incorrect),
      ],
      explanation: "Items listed in braces are imported unqualified, allowing map(...) instead of list.map(...).",
    ),
    Question(
      prompt: "Why can two different modules define functions with the same name?",
      answers: [
        Answer(
          text: "Module qualification keeps their names separate",
          correctness: Correct,
        ),
        Answer(text: "Only one function is compiled", correctness: Incorrect),
        Answer(text: "Gleam renames functions randomly", correctness: Incorrect),
        Answer(
          text: "Function names are ignored at runtime",
          correctness: Incorrect,
        ),
      ],
      explanation: "Calls such as list.map and result.map identify both the module and function, avoiding a global namespace collision.",
    ),
    Question(
      prompt: "What is a module constant allowed to depend on?",
      answers: [
        Answer(text: "Other constant expressions", correctness: Correct),
        Answer(text: "User input read at startup", correctness: Incorrect),
        Answer(text: "Any function call", correctness: Incorrect),
        Answer(text: "A mutable global variable", correctness: Incorrect),
      ],
      explanation: "Module constants are evaluated from constant expressions at compile time rather than by executing arbitrary functions.",
    ),
    Question(
      prompt: "What does todo do when evaluated?",
      answers: [
        Answer(text: "Panics to mark unfinished code", correctness: Correct),
        Answer(text: "Returns Nil", correctness: Incorrect),
        Answer(
          text: "Creates a compiler error in every case",
          correctness: Incorrect,
        ),
        Answer(text: "Skips the current function", correctness: Incorrect),
      ],
      explanation: "todo is useful while developing because it can inhabit any expected type, but evaluating it causes a panic.",
    ),
    Question(
      prompt: "What is the intended use of panic?",
      answers: [
        Answer(
          text: "Stopping on an unrecoverable programmer error",
          correctness: Correct,
        ),
        Answer(
          text: "Representing routine validation failures",
          correctness: Incorrect,
        ),
        Answer(text: "Returning an empty Option", correctness: Incorrect),
        Answer(
          text: "Retrying a failed network request",
          correctness: Incorrect,
        ),
      ],
      explanation: "Expected failures belong in Result or Option. panic is for states from which the program cannot sensibly recover.",
    ),
    Question(
      prompt: "What does a let pattern require?",
      answers: [
        Answer(
          text: "A pattern that always matches the value's type",
          correctness: Correct,
        ),
        Answer(
          text: "A pattern containing a wildcard for every value that may not match",
          correctness: Incorrect,
        ),
        Answer(text: "A Result value", correctness: Incorrect),
        Answer(text: "A guard expression", correctness: Incorrect),
      ],
      explanation: "Plain let bindings must be irrefutable. Use case for alternatives or let assert when failure truly indicates a bug.",
    ),
    Question(
      prompt: "What does the wildcard pattern _ do?",
      answers: [
        Answer(text: "Matches a value without binding it", correctness: Correct),
        Answer(text: "Matches only Nil", correctness: Incorrect),
        Answer(text: "Copies the previous binding", correctness: Incorrect),
        Answer(text: "Makes a pattern optional", correctness: Incorrect),
      ],
      explanation: "The wildcard accepts any value when that value is not needed in the clause body.",
    ),
    Question(
      prompt: "Why might a variable name begin with an underscore?",
      answers: [
        Answer(
          text: "To show it may intentionally be unused",
          correctness: Correct,
        ),
        Answer(text: "To make it globally accessible", correctness: Incorrect),
        Answer(text: "To make its value optional", correctness: Incorrect),
        Answer(text: "To disable type checking", correctness: Incorrect),
      ],
      explanation: "A leading underscore communicates intentional non-use and avoids the compiler warning produced for an ordinary unused binding.",
    ),
    Question(
      prompt: "What does True && False evaluate to?",
      answers: [
        Answer(text: "False", correctness: Correct),
        Answer(text: "True", correctness: Incorrect),
        Answer(text: "Nil", correctness: Incorrect),
        Answer(text: "Error(False)", correctness: Incorrect),
      ],
      explanation: "The && operator is Boolean conjunction, so both operands must be True for the result to be True.",
    ),
    Question(
      prompt: "What is special about && and || evaluation?",
      answers: [
        Answer(
          text: "They short-circuit when the result is already known",
          correctness: Correct,
        ),
        Answer(
          text: "They accept any type and convert each operand to a Boolean before evaluation",
          correctness: Incorrect,
        ),
        Answer(
          text: "They always evaluate right-to-left",
          correctness: Incorrect,
        ),
        Answer(text: "They return Option(Bool)", correctness: Incorrect),
      ],
      explanation: "The right operand is evaluated only when needed: && stops after False and || stops after True.",
    ),
    Question(
      prompt: "Which operator gives the remainder of integer division?",
      answers: [
        Answer(text: "%", correctness: Correct),
        Answer(text: "%%", correctness: Incorrect),
        Answer(text: "mod", correctness: Incorrect),
        Answer(text: "/.", correctness: Incorrect),
      ],
      explanation: "The % operator computes the integer remainder, while / performs integer division.",
    ),
    Question(
      prompt: "Can Gleam implicitly add an Int to a Float?",
      answers: [
        Answer(
          text: "No, numeric types are not implicitly converted",
          correctness: Correct,
        ),
        Answer(
          text: "Yes, the Int becomes a Float whenever the expression uses a Float operator",
          correctness: Incorrect,
        ),
        Answer(text: "Yes, the Float becomes an Int", correctness: Incorrect),
        Answer(text: "Only on the JavaScript target", correctness: Incorrect),
      ],
      explanation: "Int and Float are distinct types with distinct operators. Conversion must be explicit.",
    ),
    Question(
      prompt: "What does int.parse return for text that is not an integer?",
      answers: [
        Answer(text: "An Error value", correctness: Correct),
        Answer(text: "0", correctness: Incorrect),
        Answer(text: "None", correctness: Incorrect),
        Answer(text: "An empty string", correctness: Incorrect),
      ],
      explanation: "Parsing can fail, so int.parse reports success or failure with Result rather than inventing a fallback number.",
    ),
    Question(
      prompt: "How are Gleam strings encoded?",
      answers: [
        Answer(text: "As UTF-8 text", correctness: Correct),
        Answer(text: "As ASCII only", correctness: Incorrect),
        Answer(text: "As UTF-32 arrays", correctness: Incorrect),
        Answer(text: "As lists of Int values", correctness: Incorrect),
      ],
      explanation: "Gleam strings are UTF-8, so byte size and the number of human-readable characters are not always the same.",
    ),
    Question(
      prompt: "Why is string.length not always the number of visible symbols a person sees?",
      answers: [
        Answer(
          text: "Unicode graphemes can contain multiple codepoints",
          correctness: Correct,
        ),
        Answer(
          text: "Strings include a hidden null terminator",
          correctness: Incorrect,
        ),
        Answer(text: "The function counts words", correctness: Incorrect),
        Answer(text: "Length is random on JavaScript", correctness: Incorrect),
      ],
      explanation: "Unicode text can combine several codepoints into one displayed grapheme, making text measurement more nuanced than ASCII counting.",
    ),
    Question(
      prompt: "What does a bit array represent?",
      answers: [
        Answer(
          text: "A sequence of bits with typed segment patterns",
          correctness: Correct,
        ),
        Answer(
          text: "A mutable list of Boolean values in which each item occupies one bit",
          correctness: Incorrect,
        ),
        Answer(text: "A set containing only 0 and 1", correctness: Incorrect),
        Answer(text: "A compressed String", correctness: Incorrect),
      ],
      explanation: "Bit arrays are designed for binary data and protocols. Their syntax can construct and pattern match segments with sizes and encodings.",
    ),
    Question(
      prompt: "What can a bit-array pattern help parse?",
      answers: [
        Answer(
          text: "Structured binary formats and network protocols",
          correctness: Correct,
        ),
        Answer(
          text: "Only Gleam source files that have already been compiled into JavaScript",
          correctness: Incorrect,
        ),
        Answer(text: "CSS class names", correctness: Incorrect),
        Answer(text: "Database rows without decoding", correctness: Incorrect),
      ],
      explanation: "Segment options let patterns describe binary layouts, making bit arrays useful for decoding headers, packets, and file formats.",
    ),
    Question(
      prompt: "Why is prepending usually preferable to repeatedly appending to a List?",
      answers: [
        Answer(
          text: "Prepending is constant time for linked lists",
          correctness: Correct,
        ),
        Answer(text: "Appending mutates every element", correctness: Incorrect),
        Answer(text: "Gleam forbids appending", correctness: Incorrect),
        Answer(
          text: "Prepending automatically sorts the list",
          correctness: Incorrect,
        ),
      ],
      explanation: "A new head can point directly to the existing list. Reaching the end to append requires walking the list.",
    ),
    Question(
      prompt: "What does list.reverse change?",
      answers: [
        Answer(
          text: "It returns a new list in the opposite order",
          correctness: Correct,
        ),
        Answer(text: "It mutates the original list", correctness: Incorrect),
        Answer(text: "It reverses each element's bytes", correctness: Incorrect),
        Answer(
          text: "It sorts from largest to smallest",
          correctness: Incorrect,
        ),
      ],
      explanation: "Like other Gleam collection operations, list.reverse produces a new immutable value.",
    ),
    Question(
      prompt: "What does list.flatten do?",
      answers: [
        Answer(
          text: "Combines a list of lists into one list",
          correctness: Correct,
        ),
        Answer(text: "Removes every duplicate", correctness: Incorrect),
        Answer(text: "Sorts nested lists", correctness: Incorrect),
        Answer(text: "Converts a list into a tuple", correctness: Incorrect),
      ],
      explanation: "Flatten removes one level of list nesting by concatenating the inner lists in order.",
    ),
    Question(
      prompt: "When is list.filter_map useful?",
      answers: [
        Answer(
          text: "When transforming items while discarding some of them",
          correctness: Correct,
        ),
        Answer(
          text: "When mutating selected list positions while leaving other values unchanged",
          correctness: Incorrect,
        ),
        Answer(
          text: "When every item must produce an Error",
          correctness: Incorrect,
        ),
        Answer(text: "When sorting with a comparator", correctness: Incorrect),
      ],
      explanation: "The mapping function returns Option values; Some results are kept and unwrapped, while None results are omitted.",
    ),
    Question(
      prompt: "What does option.map do with None?",
      answers: [
        Answer(
          text: "Returns None without calling the function",
          correctness: Correct,
        ),
        Answer(
          text: "Calls the mapping function with Nil and wraps the returned value in Some",
          correctness: Incorrect,
        ),
        Answer(text: "Converts it to Error(Nil)", correctness: Incorrect),
        Answer(text: "Panics", correctness: Incorrect),
      ],
      explanation: "option.map transforms the value inside Some and preserves absence when given None.",
    ),
    Question(
      prompt: "What happens when dict.insert uses a key already present?",
      answers: [
        Answer(
          text: "The new dictionary contains the replacement value",
          correctness: Correct,
        ),
        Answer(
          text: "Both values are stored under the key and returned together by lookup",
          correctness: Incorrect,
        ),
        Answer(
          text: "The original dictionary is mutated",
          correctness: Incorrect,
        ),
        Answer(
          text: "The operation always returns Error",
          correctness: Incorrect,
        ),
      ],
      explanation: "Dictionary keys are unique. Inserting an existing key returns a new dictionary in which that key maps to the new value.",
    ),
    Question(
      prompt: "What does dict.get communicate through Result?",
      answers: [
        Answer(text: "Whether the requested key exists", correctness: Correct),
        Answer(text: "Whether the dictionary is sorted", correctness: Incorrect),
        Answer(text: "Whether the value is mutable", correctness: Incorrect),
        Answer(text: "Whether the key is a String", correctness: Incorrect),
      ],
      explanation: "Looking up a key may fail, so dict.get returns Ok(value) when present and an Error when absent.",
    ),
    Question(
      prompt: "What benefit do iterators provide for a chain of collection operations?",
      answers: [
        Answer(
          text: "They can avoid creating an intermediate list at every step",
          correctness: Correct,
        ),
        Answer(
          text: "They make collection elements mutable until the complete chain has been evaluated",
          correctness: Incorrect,
        ),
        Answer(
          text: "They run every operation concurrently",
          correctness: Incorrect,
        ),
        Answer(text: "They disable type inference", correctness: Incorrect),
      ],
      explanation: "Iterator pipelines can compose transformations lazily and collect the final results when needed.",
    ),
    Question(
      prompt: "What must a recursive function include to terminate normally?",
      answers: [
        Answer(text: "A reachable base case", correctness: Correct),
        Answer(text: "A mutable counter", correctness: Incorrect),
        Answer(text: "A use expression", correctness: Incorrect),
        Answer(text: "An external function", correctness: Incorrect),
      ],
      explanation: "The base case returns without another recursive call. Recursive branches must make progress toward it.",
    ),
    Question(
      prompt: "Why is an accumulator common in tail-recursive functions?",
      answers: [
        Answer(
          text: "It carries partial results into the next call",
          correctness: Correct,
        ),
        Answer(
          text: "It makes partial results mutable so recursive calls can update them in place",
          correctness: Incorrect,
        ),
        Answer(text: "It disables stack reuse", correctness: Incorrect),
        Answer(text: "It automatically catches errors", correctness: Incorrect),
      ],
      explanation: "An accumulator turns work that would happen after recursion into arguments for the next call, often enabling tail-call optimisation.",
    ),
    Question(
      prompt: "What happens when use receives an Error in a Result-sequencing helper?",
      answers: [
        Answer(
          text: "The helper can return early without running the continuation",
          correctness: Correct,
        ),
        Answer(
          text: "The compiler converts the Error into Ok and continues with the remaining block",
          correctness: Incorrect,
        ),
        Answer(
          text: "The rest of the block always runs",
          correctness: Incorrect,
        ),
        Answer(text: "The process must crash", correctness: Incorrect),
      ],
      explanation: "use itself is general callback syntax; with Result helpers, the helper decides to continue for Ok or propagate Error.",
    ),
    Question(
      prompt: "Why does Result have two type parameters?",
      answers: [
        Answer(
          text: "Success and error values can have different types",
          correctness: Correct,
        ),
        Answer(
          text: "One parameter is for each compilation target",
          correctness: Incorrect,
        ),
        Answer(
          text: "Every Result stores two successes",
          correctness: Incorrect,
        ),
        Answer(
          text: "The second parameter is always Nil",
          correctness: Incorrect,
        ),
      ],
      explanation: "Result(value, error) describes both the Ok payload type and the Error payload type.",
    ),
    Question(
      prompt: "What advantage comes from defining a custom error type?",
      answers: [
        Answer(
          text: "Callers can exhaustively handle distinct failure cases",
          correctness: Correct,
        ),
        Answer(
          text: "Errors no longer need returning because the compiler handles each failure",
          correctness: Incorrect,
        ),
        Answer(
          text: "The compiler retries failed operations",
          correctness: Incorrect,
        ),
        Answer(text: "Every error becomes a String", correctness: Incorrect),
      ],
      explanation: "Variants give failures precise structure, and exhaustive pattern matching keeps handling aligned as cases evolve.",
    ),
    Question(
      prompt: "What is checked when pattern matching an opaque type outside its module?",
      answers: [
        Answer(
          text: "Its hidden constructors cannot be matched directly",
          correctness: Correct,
        ),
        Answer(
          text: "Only wildcard patterns are forbidden because they could expose the representation",
          correctness: Incorrect,
        ),
        Answer(
          text: "The type becomes dynamically typed",
          correctness: Incorrect,
        ),
        Answer(text: "Its fields become mutable", correctness: Incorrect),
      ],
      explanation: "Opacity preserves the module boundary: consumers use public functions rather than depending on private representation details.",
    ),
    Question(
      prompt: "What can exhaustiveness checking reveal after adding a custom-type variant?",
      answers: [
        Answer(
          text: "Case expressions that need to handle the new variant",
          correctness: Correct,
        ),
        Answer(
          text: "Every dependency that became unused after the new constructor was added",
          correctness: Incorrect,
        ),
        Answer(text: "All slow functions", correctness: Incorrect),
        Answer(text: "Every possible runtime exception", correctness: Incorrect),
      ],
      explanation: "The compiler points to pattern matches that no longer cover every possible shape, making type evolution safer.",
    ),
    Question(
      prompt: "Why are custom-type constructors capitalised?",
      answers: [
        Answer(
          text: "They are distinguished from variable and function names",
          correctness: Correct,
        ),
        Answer(
          text: "They are global constants available without importing their custom type",
          correctness: Incorrect,
        ),
        Answer(text: "They bypass type checking", correctness: Incorrect),
        Answer(text: "They run at compile time", correctness: Incorrect),
      ],
      explanation: "PascalCase constructors are syntactically distinct from snake_case bindings, which helps patterns remain unambiguous.",
    ),
    Question(
      prompt: "What does @target(erlang) on a definition mean?",
      answers: [
        Answer(
          text: "The definition is compiled only for the Erlang target",
          correctness: Correct,
        ),
        Answer(
          text: "The entire package can no longer target JavaScript",
          correctness: Incorrect,
        ),
        Answer(
          text: "The function runs on a remote Erlang node",
          correctness: Incorrect,
        ),
        Answer(
          text: "All arguments must be Erlang terms",
          correctness: Incorrect,
        ),
      ],
      explanation: "Target attributes allow target-specific definitions while the rest of a module or package can remain portable.",
    ),
    Question(
      prompt: "What does @target(javascript) help isolate?",
      answers: [
        Answer(
          text: "Code available only when compiling to JavaScript",
          correctness: Correct,
        ),
        Answer(
          text: "CSS and static assets that should be included only in browser builds",
          correctness: Incorrect,
        ),
        Answer(text: "Functions that return strings", correctness: Incorrect),
        Answer(text: "Tests that run in a browser", correctness: Incorrect),
      ],
      explanation: "The attribute marks definitions whose implementation or dependencies are specific to the JavaScript target.",
    ),
    Question(
      prompt: "On which target are BEAM processes directly available?",
      answers: [
        Answer(text: "Erlang", correctness: Correct),
        Answer(text: "JavaScript", correctness: Incorrect),
        Answer(text: "WebAssembly", correctness: Incorrect),
        Answer(text: "CSS", correctness: Incorrect),
      ],
      explanation: "Lightweight BEAM processes and their mailboxes are capabilities of the Erlang runtime target.",
    ),
    Question(
      prompt: "How do Erlang processes primarily communicate?",
      answers: [
        Answer(text: "By sending immutable messages", correctness: Correct),
        Answer(text: "By sharing mutable objects", correctness: Incorrect),
        Answer(text: "By editing global variables", correctness: Incorrect),
        Answer(text: "By calling browser events", correctness: Incorrect),
      ],
      explanation: "Each process has its own mailbox and state. Message passing avoids relying on shared mutable memory.",
    ),
    Question(
      prompt: "What does linking two BEAM processes provide?",
      answers: [
        Answer(
          text: "A failure signal relationship between them",
          correctness: Correct,
        ),
        Answer(
          text: "Shared access to all local variables",
          correctness: Incorrect,
        ),
        Answer(text: "A combined mailbox", correctness: Incorrect),
        Answer(text: "Automatic HTTP communication", correctness: Incorrect),
      ],
      explanation: "Links propagate exit signals, forming part of Erlang's fault-tolerance and supervision model.",
    ),
    Question(
      prompt: "What is an actor responsible for in the actor model?",
      answers: [
        Answer(
          text: "Its own state and handling incoming messages",
          correctness: Correct,
        ),
        Answer(
          text: "Mutating every other actor's state",
          correctness: Incorrect,
        ),
        Answer(text: "Compiling imported modules", correctness: Incorrect),
        Answer(text: "Rendering CSS without messages", correctness: Incorrect),
      ],
      explanation: "Actors encapsulate state and process messages one at a time, communicating with other actors by sending messages.",
    ),
    Question(
      prompt: "Why must external function type declarations be accurate?",
      answers: [
        Answer(
          text: "The Gleam compiler trusts that boundary",
          correctness: Correct,
        ),
        Answer(text: "They determine code formatting", correctness: Incorrect),
        Answer(
          text: "They are used only for documentation",
          correctness: Incorrect,
        ),
        Answer(text: "They make native code immutable", correctness: Incorrect),
      ],
      explanation: "Native code is outside Gleam's type checking. An incorrect external declaration can break the guarantees expected by Gleam code.",
    ),
    Question(
      prompt: "What is gleam.toml primarily used for?",
      answers: [
        Answer(
          text: "Package metadata, dependencies, and build configuration",
          correctness: Correct,
        ),
        Answer(
          text: "Storing the compiled JavaScript and Erlang output for a package",
          correctness: Incorrect,
        ),
        Answer(text: "Writing unit-test assertions", correctness: Incorrect),
        Answer(text: "Defining HTML elements", correctness: Incorrect),
      ],
      explanation: "The project manifest names and configures the package and declares the packages it depends on.",
    ),
    Question(
      prompt: "Where are test-only package dependencies normally declared?",
      answers: [
        Answer(
          text: "In the dev-dependencies section of gleam.toml",
          correctness: Correct,
        ),
        Answer(
          text: "Inside every test function that imports code from the additional package",
          correctness: Incorrect,
        ),
        Answer(text: "In manifest.toml by hand", correctness: Incorrect),
        Answer(text: "As custom-type variants", correctness: Incorrect),
      ],
      explanation: "Development dependencies support testing and tooling without becoming normal runtime dependencies of the package.",
    ),
    Question(
      prompt: "What does gleam format provide?",
      answers: [
        Answer(
          text: "A consistent canonical style for Gleam source",
          correctness: Correct,
        ),
        Answer(text: "Runtime performance profiling", correctness: Incorrect),
        Answer(
          text: "Automatic type generation from JSON",
          correctness: Incorrect,
        ),
        Answer(text: "Package publication", correctness: Incorrect),
      ],
      explanation: "The formatter removes most style debates and keeps source layout consistent across a project.",
    ),
    Question(
      prompt: "What does gleam test conventionally run?",
      answers: [
        Answer(text: "The project's test main module", correctness: Correct),
        Answer(text: "Only functions named test in src", correctness: Incorrect),
        Answer(text: "A browser compatibility scanner", correctness: Incorrect),
        Answer(text: "The Hex package publisher", correctness: Incorrect),
      ],
      explanation: "Gleam test projects commonly use a test module and a library such as gleeunit to discover and run test functions.",
    ),
    Question(
      prompt: "What prefix marks a documentation comment?",
      answers: [
        Answer(text: "///", correctness: Correct),
        Answer(text: "//", correctness: Incorrect),
        Answer(text: "#", correctness: Incorrect),
        Answer(text: "<!--", correctness: Incorrect),
      ],
      explanation: "Triple-slash comments document the following public definition and can appear in generated package documentation.",
    ),
    Question(
      prompt: "What is Hex in the Gleam ecosystem?",
      answers: [
        Answer(
          text: "A package registry used to publish and fetch packages",
          correctness: Correct,
        ),
        Answer(
          text: "A binary numeric type used when encoding packages for the Erlang target",
          correctness: Incorrect,
        ),
        Answer(text: "The JavaScript compiler", correctness: Incorrect),
        Answer(text: "A browser testing framework", correctness: Incorrect),
      ],
      explanation: "Gleam packages can be distributed through Hex and added to projects as versioned dependencies.",
    ),
    Question(
      prompt: "Why does a package lock its dependency versions in a manifest?",
      answers: [
        Answer(
          text: "To make dependency resolution reproducible",
          correctness: Correct,
        ),
        Answer(text: "To prevent source formatting", correctness: Incorrect),
        Answer(text: "To hide package names", correctness: Incorrect),
        Answer(
          text: "To choose the compilation target at runtime",
          correctness: Incorrect,
        ),
      ],
      explanation: "A resolved manifest lets collaborators and automated builds use the same package versions.",
    ),
    Question(
      prompt: "In semantic versioning, what usually signals a breaking public API change?",
      answers: [
        Answer(text: "A major version increase", correctness: Correct),
        Answer(text: "A patch version increase", correctness: Incorrect),
        Answer(text: "No version change", correctness: Incorrect),
        Answer(text: "A dependency download", correctness: Incorrect),
      ],
      explanation: "For stable releases, semantic versioning reserves major-version changes for incompatible public API changes.",
    ),
    Question(
      prompt: "In Lustre's architecture, what does update produce from a model and message?",
      answers: [
        Answer(
          text: "The next model, optionally alongside effects",
          correctness: Correct,
        ),
        Answer(
          text: "A mutable DOM node containing all changes required for the next browser frame",
          correctness: Incorrect,
        ),
        Answer(text: "A CSS stylesheet", correctness: Incorrect),
        Answer(text: "A database transaction", correctness: Incorrect),
      ],
      explanation: "Lustre applications evolve explicitly: messages describe events and update calculates the next application state.",
    ),
    Question(
      prompt: "What is the job of a Lustre view function?",
      answers: [
        Answer(
          text: "Describe UI elements from the current model",
          correctness: Correct,
        ),
        Answer(text: "Mutate the model directly", correctness: Incorrect),
        Answer(text: "Compile Gleam dependencies", correctness: Incorrect),
        Answer(
          text: "Store browser cookies automatically",
          correctness: Incorrect,
        ),
      ],
      explanation: "The view is a declarative description of the interface for a given model, with events producing messages.",
    ),
    Question(
      prompt: "Why are Lustre messages represented with a custom type?",
      answers: [
        Answer(
          text: "Every application event can be handled explicitly",
          correctness: Correct,
        ),
        Answer(
          text: "Messages must be converted to HTML before update can process them",
          correctness: Incorrect,
        ),
        Answer(
          text: "Custom types make the DOM mutable",
          correctness: Incorrect,
        ),
        Answer(
          text: "Browsers require PascalCase events",
          correctness: Incorrect,
        ),
      ],
      explanation: "A custom Msg type enumerates the events that can change state, and update can pattern match them exhaustively.",
    ),
    Question(
      prompt: "What should a Lustre event handler generally return?",
      answers: [
        Answer(text: "A message for the update function", correctness: Correct),
        Answer(text: "A replacement HTML document", correctness: Incorrect),
        Answer(text: "A mutated model reference", correctness: Incorrect),
        Answer(text: "A CSS selector", correctness: Incorrect),
      ],
      explanation: "Events are translated into typed messages, keeping browser interaction connected to the application's update logic.",
    ),
    Question(
      prompt: "Why should Lustre keep side effects separate from pure state transitions?",
      answers: [
        Answer(
          text: "It keeps state logic predictable and easier to test",
          correctness: Correct,
        ),
        Answer(
          text: "It makes every effect run twice so state can verify the external result",
          correctness: Incorrect,
        ),
        Answer(text: "It removes the need for messages", correctness: Incorrect),
        Answer(text: "It makes the model mutable", correctness: Incorrect),
      ],
      explanation: "Separating effects from model calculation preserves a clear data flow and lets pure update logic be tested with ordinary values.",
    ),
  ]
}
