pub type Answer {
  Answer(text: String, is_correct: Bool)
}

pub type Question {
  Question(prompt: String, answers: List(Answer), explanation: String)
}

pub fn all() -> List(Question) {
  [
    Question(
      prompt: "What do the variants of a Gleam custom type represent?",
      answers: [
        Answer(
          text: "The different shapes a value of that type can have",
          is_correct: True,
        ),
        Answer(text: "Methods inherited by the type", is_correct: False),
        Answer(text: "Runtime subclasses", is_correct: False),
        Answer(text: "Files generated by the compiler", is_correct: False),
      ],
      explanation: "Each constructor defines one possible shape of the custom type. Pattern matching lets you handle every shape explicitly.",
    ),
    Question(
      prompt: "What is a record in Gleam?",
      answers: [
        Answer(
          text: "A custom-type variant that contains labelled or positional fields",
          is_correct: True,
        ),
        Answer(text: "A mutable JavaScript-style object", is_correct: False),
        Answer(text: "A row returned from a database", is_correct: False),
        Answer(text: "A special kind of dictionary", is_correct: False),
      ],
      explanation: "A record is a custom-type constructor that holds data. A single-variant custom type is often used like a struct.",
    ),
    Question(
      prompt: "What must a case expression do in Gleam?",
      answers: [
        Answer(text: "Match every possible value", is_correct: True),
        Answer(text: "Return a Boolean", is_correct: False),
        Answer(text: "Contain an else branch", is_correct: False),
        Answer(text: "Perform a side effect", is_correct: False),
      ],
      explanation: "Gleam checks case expressions for exhaustiveness, so adding a new variant can reveal every place that must handle it.",
    ),
    Question(
      prompt: "What does the list pattern [first, ..rest] establish?",
      answers: [
        Answer(
          text: "The list is non-empty, binding its first item and remaining items",
          is_correct: True,
        ),
        Answer(text: "The list contains exactly two items", is_correct: False),
        Answer(text: "The list is sorted", is_correct: False),
        Answer(text: "The list can be mutated", is_correct: False),
      ],
      explanation: "The pattern only matches non-empty lists. An empty-list pattern is needed for the other possible shape.",
    ),
    Question(
      prompt: "What does [new_item, ..existing_items] do?",
      answers: [
        Answer(
          text: "Creates a new list with new_item at the front",
          is_correct: True,
        ),
        Answer(text: "Mutates existing_items in place", is_correct: False),
        Answer(text: "Appends new_item to the end", is_correct: False),
        Answer(text: "Creates a nested list", is_correct: False),
      ],
      explanation: "Gleam lists are immutable linked lists. Prepending creates a new front node and leaves the existing list unchanged.",
    ),
    Question(
      prompt: "Which value is a tuple containing an Int and a String?",
      answers: [
        Answer(text: "#(42, \"Gleam\")", is_correct: True),
        Answer(text: "[42, \"Gleam\"]", is_correct: False),
        Answer(text: "{42, \"Gleam\"}", is_correct: False),
        Answer(text: "Tuple(42, \"Gleam\")", is_correct: False),
      ],
      explanation: "Tuple syntax uses #(...). Unlike a list, a tuple can contain values of different types in fixed positions.",
    ),
    Question(
      prompt: "What does Gleam's Result type represent?",
      answers: [
        Answer(
          text: "A value that can be successful or contain an error",
          is_correct: True,
        ),
        Answer(
          text: "A value that may or may not be present",
          is_correct: False,
        ),
        Answer(text: "A collection with exactly two items", is_correct: False),
        Answer(text: "A delayed side effect", is_correct: False),
      ],
      explanation: "Result(value, error) has the variants Ok(value) and Error(error), making failure part of the function's return type.",
    ),
    Question(
      prompt: "When is Option(value) the most natural model?",
      answers: [
        Answer(
          text: "When a value may be present or absent without error details",
          is_correct: True,
        ),
        Answer(
          text: "When an operation has several error reasons",
          is_correct: False,
        ),
        Answer(text: "When a value changes over time", is_correct: False),
        Answer(text: "When a function returns two values", is_correct: False),
      ],
      explanation: "Option(value) has Some(value) and None. Use Result when the failure itself carries useful information.",
    ),
    Question(
      prompt: "What does the pipeline operator pass to the next function?",
      answers: [
        Answer(text: "The value on its left", is_correct: True),
        Answer(text: "The function's return type", is_correct: False),
        Answer(text: "The current module", is_correct: False),
        Answer(text: "A list of all previous values", is_correct: False),
      ],
      explanation: "The |> operator normally supplies the left-hand value as the first argument. A function capture can place it in another position.",
    ),
    Question(
      prompt: "What does the underscore mean in string.append(\"!\", _)?",
      answers: [
        Answer(
          text: "It captures a one-argument function with a placeholder",
          is_correct: True,
        ),
        Answer(text: "It discards the return value", is_correct: False),
        Answer(text: "It inserts an empty string", is_correct: False),
        Answer(text: "It marks a private function", is_correct: False),
      ],
      explanation: "Function capture syntax is shorthand for an anonymous function. Here it is equivalent to fn(value) { string.append(\"!\", value) }.",
    ),
    Question(
      prompt: "What makes a function higher-order?",
      answers: [
        Answer(
          text: "It accepts a function or returns a function",
          is_correct: True,
        ),
        Answer(text: "It is declared with pub", is_correct: False),
        Answer(text: "It contains more than one pipeline", is_correct: False),
        Answer(text: "It works only with custom types", is_correct: False),
      ],
      explanation: "Functions are ordinary values in Gleam, so they can be passed to and returned from other functions.",
    ),
    Question(
      prompt: "What does list.map([1, 2, 3], fn(x) { x * 2 }) return?",
      answers: [
        Answer(text: "[2, 4, 6]", is_correct: True),
        Answer(text: "[1, 2, 3, 2]", is_correct: False),
        Answer(text: "6", is_correct: False),
        Answer(text: "Nil", is_correct: False),
      ],
      explanation: "list.map applies the function to every element and returns a new list containing the transformed values.",
    ),
    Question(
      prompt: "What does pub change on a top-level Gleam definition?",
      answers: [
        Answer(
          text: "It makes the definition accessible from other modules",
          is_correct: True,
        ),
        Answer(text: "It makes the value mutable", is_correct: False),
        Answer(text: "It runs the definition at startup", is_correct: False),
        Answer(text: "It publishes the package to Hex", is_correct: False),
      ],
      explanation: "Top-level functions, constants, and types are private to their module unless they are declared public.",
    ),
    Question(
      prompt: "What does import gleam/string as text do?",
      answers: [
        Answer(
          text: "Imports the module under the local name text",
          is_correct: True,
        ),
        Answer(text: "Imports only a function named text", is_correct: False),
        Answer(text: "Converts every String to Text", is_correct: False),
        Answer(text: "Renames the module globally", is_correct: False),
      ],
      explanation: "A module alias only changes how that module is referred to within the importing module.",
    ),
    Question(
      prompt: "When should let assert be used?",
      answers: [
        Answer(
          text: "When failure means a programmer assumption was wrong",
          is_correct: True,
        ),
        Answer(text: "For normal user-input validation", is_correct: False),
        Answer(text: "Whenever a function returns Result", is_correct: False),
        Answer(text: "To disable exhaustiveness checking", is_correct: False),
      ],
      explanation: "let assert permits a pattern that may fail and panics if it does. Recoverable possibilities should be handled explicitly instead.",
    ),
    Question(
      prompt: "What is the main purpose of a use expression?",
      answers: [
        Answer(
          text: "To write callback-based control flow without deep nesting",
          is_correct: True,
        ),
        Answer(text: "To import another module", is_correct: False),
        Answer(text: "To mutate a value temporarily", is_correct: False),
        Answer(text: "To catch every runtime exception", is_correct: False),
      ],
      explanation: "A use expression passes the remainder of its block as a callback, making patterns such as Result sequencing read top-to-bottom.",
    ),
    Question(
      prompt: "What does Person(..person, age: 31) do?",
      answers: [
        Answer(
          text: "Creates a new record using person's fields with a new age",
          is_correct: True,
        ),
        Answer(text: "Mutates person's age in place", is_correct: False),
        Answer(text: "Pattern matches only the age field", is_correct: False),
        Answer(text: "Converts person into a tuple", is_correct: False),
      ],
      explanation: "Record update syntax constructs a new value by copying existing fields and replacing the named fields. The original remains unchanged.",
    ),
    Question(
      prompt: "What does pub opaque type protect?",
      answers: [
        Answer(
          text: "Its constructors and internal representation outside its module",
          is_correct: True,
        ),
        Answer(
          text: "The type's source code from the compiler",
          is_correct: False,
        ),
        Answer(text: "All functions that accept the type", is_correct: False),
        Answer(text: "The value from garbage collection", is_correct: False),
      ],
      explanation: "Other modules can hold an opaque value and use the defining module's public API, but they cannot construct or pattern match on its hidden representation.",
    ),
  ]
}
